services:
  backend:
    build: ./backend
    expose:
      - "3001"
    volumes:
      - ./backend/uploads:/app/uploads
      - backend_db:/app/prisma
    depends_on:
      - db_setup
    restart: unless-stopped
    env_file: .env

  frontend:
    build: ./frontend
    expose:
      - "3000"
    env_file: .env

  bridge-viewer:
    image: node:18-alpine
    working_dir: /app
    expose:
      - "3002"
    environment:
      - PORT=3002
    volumes:
      - ${BRIDGE_VIEWER_PATH}:/app
    command: sh -c "npm install && npm run serve"
    restart: unless-stopped
    env_file: .env

  db_setup:
    build: ./backend
    env_file: .env
    volumes:
      - backend_db:/app/prisma
    command: sh -c "npx prisma generate && npx prisma db push"

  caddy:
    container_name: caddy
    image: docker.io/caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    env_file: .env
    depends_on:
      - frontend

volumes:
  backend_db:
