version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prod.db
    volumes:
      - ./backend/uploads:/app/uploads
      - backend_db:/app/prisma
    depends_on:
      - db_setup
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - frontend_dist:/app/dist

  bridge-viewer:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - ${BRIDGE_VIEWER_PATH:-/tmp}:/app
    command: sh -c "npm install && npm run serve"
    restart: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - APP_ROOT=/app
    volumes:
      - frontend_dist:/app/frontend/dist
      - ./backend/uploads:/app/backend/uploads
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  db_setup:
    build: ./backend
    volumes:
      - backend_db:/app/prisma
    command: sh -c "npx prisma generate && npx prisma db push"

volumes:
  backend_db:
  frontend_dist: